### ISSUE TITLE
Consider incorporating a new section into the README.md file.

### ISSUE THREAD

**Issue by Tim-Rambo** [sschmid/pw#5]
To enhance the README.md file, please consider adding a new section that provides instructions on how to uninstall the application after it has been installed. 

Thank you. 😃

**Comment by sschmid** [comment]
Hi!
I updated the readme and as of version `7.0` you can use the command specified in the readme:
```sh
/usr/local/opt/pw/install --uninstall
```

For older versions do this:
```sh
rm -rf /usr/local/opt/pw
rm /usr/local/bin/pw
```
